version: "3.8"

services:
  # 1. Base de datos MongoDB
  mongodb:
    image: mongo:7.0
    container_name: incident_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Volumen para que los datos persistan si se apaga el contenedor
    restart: unless-stopped

  # 2. Backend API
  api:
    build:
      context: ./incident-api
      dockerfile: Dockerfile
    container_name: incident_api
    env_file:
      - ./incident-api/.env
    ports:
      - "3000:3000"
    environment:
      # Sobreescribimos solo lo que cambia en Docker (la URL de mongo usa el nombre del servicio)
      - MONGODB_URI=mongodb://mongodb:27017/incident_db
      - CORS_ORIGIN=http://localhost:8080
    depends_on:
      - mongodb
    restart: unless-stopped

  # 3. Frontend Dashboard
  dashboard:
    build:
      context: ./incident-dashboard
      dockerfile: Dockerfile
    container_name: incident_dashboard
    ports:
      - "8080:80" # Mapeamos el puerto 80 de Nginx al puerto 8080 de tu máquina
    depends_on:
      - api
    restart: unless-stopped

# Declaración del volumen para persistencia de datos
volumes:
  mongo_data:
